44 terratowns provider (#48)
* #44 wip setting up the skeleton for creating a custom terraform provider

* #44 implement terraform provider block in terraform

* #44 setup skeleton for resource

* #42 copy terratowns mok server into our repo. Move bin directories into main bin directory

 # 44 wip setting up the skeleton for creating a custom terraform provider

44 implement terraform provider block in terraform

diff --git a/bin/build_provider b/bin/build_provider
--- a/bin/build_provider
+++ b/bin/build_provider
@@ -6,7 +6,7 @@ VERSION="1.0.0"
 PLUGIN_DIR="/home/gitpod/.terraform.d/plugins/local.providers/local/terratowns/${VERSION}"
 PLUGIN_NAME="terraform-provider-terratowns_v${VERSION}"
 
-cd "${PROJECT_ROOT}/terraform-provider-terratowns"
+cd "${PROJECT_ROOT}/terraform-provider-terratowns" || exit
 cp "${PROJECT_ROOT}/terraformrc" /home/gitpod/.terraformrc
 
 
@@ -15,9 +15,22 @@ rm -rf "${PROJECT_ROOT}/.terraform.d"
 rm -rf "${PROJECT_ROOT}/.terraform.lock.hcl" 
 
 go build -o "${PLUGIN_NAME}"
+if [ $? -ne 0 ] ; then
+    echo "ERROR: Build did not work"
+    exit 1
+fi
 
 mkdir -p "${PLUGIN_DIR}/x86_64"
 mkdir -p "${PLUGIN_DIR}/linux_amd64"
 
 cp "${PLUGIN_NAME}" "${PLUGIN_DIR}/x86_64/"
+if [ $? -ne 0 ] ; then
+    echo "ERROR: copy to x86_64 failed"
+    exit 1
+fi
+
 cp "${PLUGIN_NAME}" "${PLUGIN_DIR}/linux_amd64/"
+if [ $? -ne 0 ] ; then
+    echo "ERROR: copy to amd64 failed"
+    exit 1
+fi
